stages:
#  - build
#  - test
#  - package
  - deploy

variables:
#  MAVEN_CLI_OPTS: "-s $CI_PROJECT_DIR/.m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  CLI_VERSION: 6.2.1
  OPENSHIFT_SERVER: "https://api.us-east-2.online-starter.openshift.com:6443"
  OPENSHIFT_DOMAIN: "apps.us-east-2.online-starter.openshift.com"

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository/
    - backend/target/
    - frontend/node_modules/

deploy-versioning:
  stage: deploy
  image: ebits/openshift-client
  variables:
    APP: versioning
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  before_script:
    - "echo OPENSHIFT_SERVER: $OPENSHIFT_SERVER"
    - "echo OPENSHIFT_TOKEN: $OPENSHIFT_TOKEN"
    - wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/4.1/linux/oc.tar.gz
    - tar x -f oc.tar.gz
    - echo $PATH
    - ls -l
    - cp oc /usr/bin
    - oc login --server="$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
  script:
    - mkdir -p build
    - mkdir -p build/deployments
    - cp -r .s2i build
    - cp -r frontend/dist/frontend.war build/deployments
    - cp -r backend/target/*.war build/deployments
    - ls -l build
    - ls -l build/deployments
#    - "oc get services $APP 2> /dev/null || oc new-app . --name=$APP --strategy=docker"
#    - "oc start-build $APP --from-dir=. --follow || sleep 3s && oc start-build $APP --from-dir=. --follow"
#    - "oc get routes $APP  || oc expose service $APP --hostname=$APP_HOST"
    - "echo end"
  environment:
    name: *
    url: http://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master
