stages:
  - build
  - test
  - package
  - deploy

variables:
#  MAVEN_CLI_OPTS: "-s $CI_PROJECT_DIR/.m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  CLI_VERSION: 6.2.1
  OPENSHIFT_DOMAIN: "apps.us-east-2.online-starter.openshift.com"

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository/
    - backend/target/
    - frontend/node_modules/

build-backend:
  stage: build
  image: maven:latest
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

build-frontend:
  stage: build
  image: trion/ng-cli
  before_script:
    - cd frontend
    - npm ci
  script:
    - rm -f dist/frontend
    - ng build

test-backend:
  stage: test
  image: maven:latest
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test

test-frontend:karma:
  stage: test
  image: trion/ng-cli-karma:${CLI_VERSION}
  allow_failure: false
  before_script:
    - cd frontend
  script:
    - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI

package-backend:
  stage: package
  image: maven:latest
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - backend/target/*.war

package-frontend:
  stage: package
  image: trion/ng-cli
  before_script:
    - cd frontend
    - npm ci
  script:
    - rm -f dist/frontend
    - ng build --progress false --prod --base-href "/frontend/"
  artifacts:
    paths:
     - frontend/dist/frontend.war

deploy-versioning:
  stage: package
  image: ayufan/openshift-cli
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc project "$CI_PROJECT_NAME" 2> /dev/null
  script:
    - "oc get services $APP 2> /dev/null || oc new-app . --name=$APP --strategy=docker"
#    - "oc start-build $APP --from-dir=. --follow || sleep 3s && oc start-build $APP --from-dir=. --follow"
#    - "oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST"

production:
  <<: *deploy
  stage: production
  variables:
    APP: versioning
    APP_HOST: $CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  when: manual
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$OPENSHIFT_DOMAIN
  only:
    - master
