stages:
  - build
  - test
  - package

variables:
#  MAVEN_CLI_OPTS: "-s $CI_PROJECT_DIR/.m2/settings.xml --batch-mode"
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository/
    - backend/target/

build-backend:
  stage: build
  image: maven:latest
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS compile

test-backend:
  stage: test
  image: maven:latest
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test

package-backend:
  stage: package
  image: maven:latest
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS package
